/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipMembersRouteImport } from './routes/vip-members'
import { Route as SponsorshipRouteImport } from './routes/sponsorship'
import { Route as SheTalksRouteImport } from './routes/she-talks'
import { Route as RiseToSkyRouteImport } from './routes/rise-to-sky'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VipMembersRoute = VipMembersRouteImport.update({
  id: '/vip-members',
  path: '/vip-members',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipRoute = SponsorshipRouteImport.update({
  id: '/sponsorship',
  path: '/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const SheTalksRoute = SheTalksRouteImport.update({
  id: '/she-talks',
  path: '/she-talks',
  getParentRoute: () => rootRouteImport,
} as any)
const RiseToSkyRoute = RiseToSkyRouteImport.update({
  id: '/rise-to-sky',
  path: '/rise-to-sky',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/rise-to-sky': typeof RiseToSkyRoute
  '/she-talks': typeof SheTalksRoute
  '/sponsorship': typeof SponsorshipRoute
  '/vip-members': typeof VipMembersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/rise-to-sky': typeof RiseToSkyRoute
  '/she-talks': typeof SheTalksRoute
  '/sponsorship': typeof SponsorshipRoute
  '/vip-members': typeof VipMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/membership': typeof MembershipRoute
  '/rise-to-sky': typeof RiseToSkyRoute
  '/she-talks': typeof SheTalksRoute
  '/sponsorship': typeof SponsorshipRoute
  '/vip-members': typeof VipMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/awards'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/membership'
    | '/rise-to-sky'
    | '/she-talks'
    | '/sponsorship'
    | '/vip-members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/awards'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/membership'
    | '/rise-to-sky'
    | '/she-talks'
    | '/sponsorship'
    | '/vip-members'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/awards'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/membership'
    | '/rise-to-sky'
    | '/she-talks'
    | '/sponsorship'
    | '/vip-members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AwardsRoute: typeof AwardsRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  MembershipRoute: typeof MembershipRoute
  RiseToSkyRoute: typeof RiseToSkyRoute
  SheTalksRoute: typeof SheTalksRoute
  SponsorshipRoute: typeof SponsorshipRoute
  VipMembersRoute: typeof VipMembersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip-members': {
      id: '/vip-members'
      path: '/vip-members'
      fullPath: '/vip-members'
      preLoaderRoute: typeof VipMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsorship': {
      id: '/sponsorship'
      path: '/sponsorship'
      fullPath: '/sponsorship'
      preLoaderRoute: typeof SponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/she-talks': {
      id: '/she-talks'
      path: '/she-talks'
      fullPath: '/she-talks'
      preLoaderRoute: typeof SheTalksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rise-to-sky': {
      id: '/rise-to-sky'
      path: '/rise-to-sky'
      fullPath: '/rise-to-sky'
      preLoaderRoute: typeof RiseToSkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AwardsRoute: AwardsRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  MembershipRoute: MembershipRoute,
  RiseToSkyRoute: RiseToSkyRoute,
  SheTalksRoute: SheTalksRoute,
  SponsorshipRoute: SponsorshipRoute,
  VipMembersRoute: VipMembersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
